---
name: Delete pre-releases

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: dev-drprasad/delete-older-releases@v0.3.2
        with:
          delete_prerelease_only: true
          delete_tags: true
          keep_latest: 0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0

      - name: Delete unstable tags
        run: git tag -l "*-unstable" | xargs -n 1 git push --delete origin
